// save.js
//
// Saving and loading, in the browser's localStorage. The world is rebuilt
// from its seed on load, so a save only holds what changed: the village's
// numbers (game.js), who owns which tile and what's left on it (hexMap),
// and the villages. Autosaved at the end of every turn (see game.js).
//
// Version 4: the world is generated by js/world/worldGen.js (several
// continents, roads, work sites), so older saves cannot be rebuilt and are
// ignored.
//
// T5 portal hardening: two slots (primary + backup of the previous good
// save), a tiny worldHash so a generator change never loads a mismatched
// map silently, and no silent loss — corrupt/old/quota failures are visible
// to the caller instead of vanishing.

const SAVE_KEY = "bottom_up.save.v1";
const SAVE_BACKUP_KEY = "bottom_up.save.v1.bak";
const SAVE_VERSION = 4;

// A cheap stable hash of what the world was generated from, so load can
// refuse a save whose map no longer matches this build's generator.
// Not cryptographic — just enough to catch "same seed, different world".
function saveWorldHash(seed, world) {
  const cols = world && world.cols ? world.cols : 0;
  const rows = world && world.rows ? world.rows : 0;
  const count = world && world.villages ? world.villages.length : 0;
  let hash = (seed >>> 0) ^ (cols * 7919) ^ (rows * 104729) ^ (count * 1299709);
  hash = ((hash >>> 16) ^ hash) >>> 0;
  hash = Math.imul(hash, 2246822519) >>> 0;
  hash = ((hash >>> 13) ^ hash) >>> 0;
  return hash >>> 0;
}

function saveRead(key) {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return null;
    const state = JSON.parse(raw);
    return state && typeof state === "object" ? state : null;
  } catch (error) {
    return null;
  }
}

function saveValid(state) {
  return !!state && state.version === SAVE_VERSION && typeof state.seed === "number";
}

function saveGame(seed) {
  const worldForHash = typeof world !== "undefined" ? world : null;
  const state = {
    version: SAVE_VERSION,
    seed,
    savedAt: new Date().toISOString(),
    worldHash: saveWorldHash(seed >>> 0, worldForHash),
    worldCols: worldForHash && worldForHash.cols ? worldForHash.cols : null,
    worldRows: worldForHash && worldForHash.rows ? worldForHash.rows : null,
    game: gameGetState(),
    map: hexMap.serialize(),
    villages: villagesGet(),
    // Raids, defences and grudges (js/raids.js); the objective checklist
    // (js/objectives.js). Both are optional so an older save still loads.
    raids: typeof raidsGetState === "function" ? raidsGetState() : null,
    objectives: typeof objectivesGetState === "function" ? objectivesGetState() : null,
    // T-fix: view state so reload keeps lens/grid/selection instead of
    // resetting the desk every load.
    view: {
      lens: typeof currentLens !== "undefined" ? currentLens : null,
      grid: typeof gridOn !== "undefined" ? !!gridOn : false,
      selected: (typeof hexMap !== "undefined" && hexMap && hexMap.selectedTileId) || null,
    },
  };
  const payload = JSON.stringify(state);
  try {
    // Keep the last good save before overwriting it.
    try {
      const previous = localStorage.getItem(SAVE_KEY);
      if (previous) localStorage.setItem(SAVE_BACKUP_KEY, previous);
    } catch (error) {
      // backup is best-effort; the primary save still matters
    }
    localStorage.setItem(SAVE_KEY, payload);
    return true;
  } catch (error) {
    // Private windows and full storage both land here. Tell the player
    // instead of carrying on unsaved in silence (main.js shows it).
    if (typeof updatelog === "function") {
      updatelog("Could not save — the browser refused storage. The game continues unsaved.", "bad");
    }
    return false;
  }
}

function loadSavedGame() {
  const primary = saveRead(SAVE_KEY);
  if (saveValid(primary)) return primary;
  // Primary missing/corrupt/old: try the backup before giving up.
  const backup = saveRead(SAVE_BACKUP_KEY);
  if (saveValid(backup)) {
    // Promote the backup so the next save keeps a chain.
    try {
      localStorage.setItem(SAVE_KEY, JSON.stringify(backup));
    } catch (error) {
      // promotion is best-effort
    }
    return backup;
  }
  return null;
}

// True if a save was made by an older build or a different generator and
// must not be trusted against this world's tiles.
function saveWorldMismatch(saved, seed, world) {
  if (!saved) return false;
  if (!saveValid(saved)) return true;
  if ((saved.seed >>> 0) !== (seed >>> 0)) return true;
  const expected = saveWorldHash(seed >>> 0, world);
  // Saves from before worldHash existed have none — trust seed + version.
  if (saved.worldHash == null) return false;
  return saved.worldHash !== expected;
}

function clearSavedGame() {
  try {
    localStorage.removeItem(SAVE_KEY);
  } catch (error) {
    // nothing to clear
  }
  try {
    localStorage.removeItem(SAVE_BACKUP_KEY);
  } catch (error) {
    // nothing to clear
  }
}
